services:
  # The Patient
  monitored-app:
    image: lukesh26/monitored-app:latest
    container_name: monitored-app
    ports:
      - "8080:8080"
    environment:
      - JAVA_TOOL_OPTIONS=-XX:+ExitOnOutOfMemoryError
    deploy:
      resources:
        limits:
          memory: 512M
    networks:
      - monitor-net

  # The Doctor
  monitoring-service:
    image: lukesh26/monitoring-service:latest
    container_name: monitoring-service
    ports:
      - "8081:8081"
    environment:
      - TARGET_SERVICE_URL=http://monitored-app:8080
      - SLACK_WEBHOOK_URL=${SLACK_WEBHOOK_URL}
      - CONTAINER_TO_RESTART=monitored-app
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      resources:
        reservations:
          memory: 256M
    depends_on:
      - monitored-app
    networks:
      - monitor-net

networks:
  monitor-net:
    driver: bridge